### PR TITLE
Port the shipping estimate module to PS 1.7

### PR DESCRIPTION
**Pull request by firstred**
screenshot from 2018-10-28 11-09-37

This pull request ports the shipping estimate module to PrestaShop 1.7.

All the functionality has been restored, but this time the `simulateCarrierOutput` function is being avoided and a regular ~~JSON~~ server side rendered response with carrier data is used instead. ~~This is then rendered with a simple Handlebars template (wrapped with Smarty to make it overrideable).~~

The `ajax.php` endpoint has been replaced by a FrontController and handles the widget's calls.

~~This module adds one library to the Javascript pool: Handlebars, a template engine. It uses `noConflict()` to make sure any previous Handlebars instance is left intact.~~

The styling has been updated for the Classic theme, with minimalistic Smarty templates to make integrations easier.

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Before any review, the 1.7 equivalent module is https://github.com/PrestaShop/ps_carriercomparison.

@eternoendless, we could think about merging the two modules if we can have a single version for 1.6 & 1.7.

**Comment by firstred** [comment]
Then how come these modules are on the roadmap and not listed in the back office?

**Comment by firstred** [comment]
I think it has stranded, like the https://github.com/PrestaShop/dateofdelivery module I saw earlier.

**Comment by Quetzacoalt91** [comment]
Well, this is our chance then to deprecate the duplicated module.
FYI, I listed the 1.7 modules I found in the documentation: https://devdocs.prestashop.com/1.7/modules/#main-differences-between-1-6-and-1-7-modules

**Comment by firstred** [comment]
Nice, thank you!

**Pull request closed without merging**
